# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-12 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_auto_20180611_1248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='NannyApplication',
        ),
        migrations.RemoveField(
            model_name='applicantpersonaldetails',
            name='application_id',
        ),
    ]
