# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-12 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0003_auto_20180612_1716'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nannyapplication',
            table='NANNY_APPLICATION',
        ),
    ]
